services:

  pingerfront:    
    container_name: pingerfront
    image: thomasreulen/pinger-frontend:v1.0.19 
    volumes:
      - ./src/:/usr/src/app
      - ./testdata/:/pinger-data
      - ./teestdata-target/:/pinger-data-target
    restart: always
    #command: tail -F anything
    ports:
      - 5000:5000